version: "3"

services:
  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./etc/nginx/vhost.d:/etc/nginx/vhost.d
      - ./usr/share/nginx/html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
    networks:
      - proxy
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    links:
      - nginx-proxy
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./etc/nginx/vhost.d:/etc/nginx/vhost.d
      - ./usr/share/nginx/html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tpl:/etc/docker-gen/templates/nginx.tpl:ro
    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tpl /etc/nginx/conf.d/default.conf
    networks:
      - proxy
      - default
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./etc/nginx/vhost.d:/etc/nginx/vhost.d
      - ./usr/share/nginx/html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      - NGINX_PROXY_CONTAINER=nginx-proxy
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - default

networks:
  proxy:
    external:
      name: proxy
