version: '3.7'

services:
    nginx-web:
        build:
            context: ./nginx
        labels:
            com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
        container_name: ${NGINX_WEB:-nginx-web}
        restart: always
        ports:
            - "${IP:-0.0.0.0}:80:80"
            - "${IP:-0.0.0.0}:443:443"
        volumes:
            - nginx-conf:/etc/nginx/conf.d
            - nginx-vhost:/etc/nginx/vhost.d
            - nginx-html:/usr/share/nginx/html
            - certs:/etc/nginx/certs:ro
            - htpasswd:/etc/nginx/htpasswd:ro
        networks:
            - proxy_app
            - proxy_api
        logging:
            driver: ${NGINX_WEB_LOG_DRIVER:-json-file}
            options:
                max-size: ${NGINX_WEB_LOG_MAX_SIZE:-4m}
                max-file: ${NGINX_WEB_LOG_MAX_FILE:-10}

    nginx-gen:
        build:
            context: .
        command: -notify-sighup ${NGINX_WEB:-nginx-web} -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        container_name: ${DOCKER_GEN:-nginx-gen}
        restart: always
        volumes:
            - nginx-conf:/etc/nginx/conf.d
            - nginx-vhost:/etc/nginx/vhost.d
            - nginx-html:/usr/share/nginx/html
            - certs:/etc/nginx/certs:ro
            - htpasswd:/etc/nginx/htpasswd:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro
            #- ./templates:/etc/docker-gen/templates:ro
        networks:
            - proxy_app
            - proxy_api
        logging:
            driver: ${NGINX_GEN_LOG_DRIVER:-json-file}
            options:
                max-size: ${NGINX_GEN_LOG_MAX_SIZE:-2m}
                max-file: ${NGINX_GEN_LOG_MAX_FILE:-10}
        depends_on:
            - nginx-web

    nginx-letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: ${LETS_ENCRYPT:-nginx-letsencrypt}
        restart: always
        volumes:
            - nginx-conf:/etc/nginx/conf.d
            - nginx-vhost:/etc/nginx/vhost.d
            - nginx-html:/usr/share/nginx/html
            - certs:/etc/nginx/certs:rw
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            NGINX_DOCKER_GEN_CONTAINER: ${DOCKER_GEN:-nginx-gen}
            NGINX_PROXY_CONTAINER: ${NGINX_WEBz:-nginx-web}
        networks:
            - proxy_app
            - proxy_api
        logging:
            driver: ${NGINX_LETSENCRYPT_LOG_DRIVER:-json-file}
            options:
                max-size: ${NGINX_LETSENCRYPT_LOG_MAX_SIZE:-2m}
                max-file: ${NGINX_LETSENCRYPT_LOG_MAX_FILE:-10}
        depends_on:
            - nginx-gen
            - nginx-web

networks:
    proxy_app:
        external: true
    proxy_api:
        external: true

volumes:
    certs:
    nginx-conf:
    nginx-vhost:
    nginx-html:
    htpasswd:
