version: "3"

services:
  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - proxy-confd:/etc/nginx/conf.d
      - proxy-vhostd:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html
      - proxy-certs:/etc/nginx/certs:ro
    networks:
      - proxy
  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - proxy-confd:/etc/nginx/conf.d
      - proxy-vhostd:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html
      - proxy-certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tpl:/etc/docker-gen/templates/nginx.tpl:ro
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tpl /etc/nginx/conf.d/default.conf
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes:
      - proxy-confd:/etc/nginx/conf.d
      - proxy-vhostd:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html
      - proxy-certs:/etc/nginx/certs:rw
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      - NGINX_PROXY_CONTAINER=nginx-proxy

volumes:
  vhost:
  proxy-confd:
  proxy-vhostd:
  proxy-html:
  proxy-certs:

networks:
  proxy:
    external:
      name: proxy