version: "3"

services:
  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
    networks:
      - proxy
      - default

  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    links:
      - nginx-proxy
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tpl:/etc/docker-gen/templates/nginx.tpl:ro
    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tpl /etc/nginx/conf.d/default.conf
    networks:
      - proxy
      - default

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      - NGINX_PROXY_CONTAINER=nginx-proxy
    networks:
      - default
    depends_on:
      - nginx-proxy
      - nginx-gen

networks:
  proxy:
    external:
      name: proxy

volumes:
    conf:
    vhost:
    html:
