version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-confd:/etc/nginx/conf.d
      - nginx-vhostd:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    networks:
      - proxy-tier
  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - nginx-confd:/etc/nginx/conf.d
      - nginx-vhostd:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tpl:/etc/docker-gen/templates/nginx.tpl:ro
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tpl /etc/nginx/conf.d/default.conf
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes:
      - nginx-confd:/etc/nginx/conf.d
      - nginx-vhostd:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      - NGINX_PROXY_CONTAINER=nginx

volumes:
  vhost:
  nginx-confd:
  nginx-vhostd:
  nginx-html:
  certs:
    driver: local
    driver_opts:
        o: bind
        type: none
        device: /etc/nginx/certs

networks:
  proxy-tier:
    external:
      name: nginx-proxy